### ISSUE TITLE
Dataset in "Good-Enough Compositional Data Augmentation"

### ISSUE THREAD

**Issue by dguo98** [jacobandreas/geca#1]
Hi Jacob!

I'm really interested in your work "good-enough compositional data augmentation", and would love to try it out! :)

Is there a processed version of the dataset or command to reproduce the SCAN/NACS/LM dataset mentioned in the paper? 

Thanks!!

**Comment by jacobandreas** [comment]
Added a README with dataset links. Still trying to figure out how to distribute the LM data

**Comment by dguo98** [comment]
Hi Jacob,
Thanks for the quick reply!  For SCAN/NACS, how could I get the GECA augmentation dataset?
Will I get the same data if I run for example exp/scan_jump/baseline/run.sh? 

Thanks again!

**Comment by jacobandreas** [comment]
Yep---just make sure to point --scan_data_dir at the location of the scan
repo.

**Comment by dguo98** [comment]
Cool! What is the difference between exp/scan_jump/baseline and exp/scan_jump/retrieval?

**Comment by jacobandreas** [comment]
Those numbers are in Table 1

**Comment by dguo98** [comment]
Hi Jacob, thanks for the quick reply!

Currently, I put all the compose*.json data in  exp/scan_jump/retrieval as well as original train data together, and train a fairseq seq2seq model. Interestingly, I got almost 100% accuracy on test set.
I wonder if I misunderstood something...

My understanding is that each compose*.json is a randomly generated subset of GECA augmentation data. So it will be fine for me to combine all these compose*.json data with original train dataset....

**Comment by jacobandreas** [comment]
Yeah---it's possible the FairSeq models are a little better than my
baseline and you'll get better results from training on the combined data.
It's correct that compose*.json contain the synthesized examples.

**Comment by dguo98** [comment]
Thanks Jacob!! 
I think I found a problem with my code... >_<

**Comment by dguo98** [comment]
Hi Jacob!

Thanks again for being super helpful!
One more question...  Could you provide the code for the geo query logic form? 
Do you run all experiments on Jia's code?

Thanks!

**Comment by jacobandreas** [comment]
Yes---just point the experiment script at the code from their codalab page.

**Comment by dguo98** [comment]
Thanks!!
